spring:
  application:
    name: ms-product
  h2: 
    console:
      enabled: true
server:
  port: 9010
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
      leaseRenewalIntervalInSeconds: 4
      leaseExpirationDurationInSeconds: 8
management:
  endpoints:
    web:
      exposure:
        include: "*"
arquitectura:
  software: "github"
