spring:
  application:
    name: ms-product
  h2:
    console:
      enabled: true
server:
  port: 9010
eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
#      leaseRenewalIntervalInSeconds: 4
#      leaseExpirationDurationInSeconds: 8
      hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include: "*"
sample:
 string:
   property: Change to config SERVER
 int:
   property: 212 